#!/bin/bash
source "/sys/class/power_supply/battery/uevent"
function get () {
        cmd="scale=$2; $1 / $3"
        data=$(bc <<< $cmd)
        echo "$data"
}
if [ "$POWER_SUPPLY_STATUS" == "Charging" ]; then
        amp_sign="+"
else
        amp_sign="-"
fi
echo "Current battery information"
echo "---------------------------"
echo "Status: $POWER_SUPPLY_STATUS"
echo "Capacity: $POWER_SUPPLY_CAPACITY%"
echo "Voltage: $(get "$POWER_SUPPLY_VOLTAGE_NOW" "3" "1000000")V / $(get "$POWER_SUPPLY_VOLTAGE_MAX_DESIGN" "3" "1000000")V"
echo "Amperage: $amp_sign$(get "$POWER_SUPPLY_CURRENT_NOW" "0" "1000")mAh"
